// APPOINTMENT
export const SET_APPOINTMENT = "SET_APPOINTMENT";
export const UPDATE_APPOINTMENT = "UPDATE_APPOINTMENT";
export const GET_APPOINTMENTS = "GET_APPOINTMENTS";
export const GET_USER_APPOINTMENTS = "GET_USER_APPOINTMENTS";
export const GET_NEXT_7_APPOINTMENTS = "GET_NEXT_7_APPOINTMENTS";
export const DELETE_APPOINTMENT = "DELETE_APPOINTMENT";
