export const GET_CART = "GET_CART";
export const GET_CART_QUANTITY = "GET_CART_QUANTITY";
export const GET_PRODUCT_QUANTITY = "GET_PRODUCT_QUANTITY";
export const ADD_TO_CART = "ADD_TO_CART";
export const UPDATE_CART = "UPDATE_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const EMPTY_CART = "EMPTY_CART";
